 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMP.View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import LMP.Control.ConnectData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class LoginFrame extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        conn=ConnectData.getConnection();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP1 = new javax.swing.JPanel();
        JUserIcon = new javax.swing.JLabel();
        JPassIcon = new javax.swing.JLabel();
        JUserText = new javax.swing.JTextField();
        JPassTxt = new javax.swing.JPasswordField();
        JLoginB = new javax.swing.JButton();
        JLReLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management Program");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(550, 195, 460, 282));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(550, 195, 460, 290));
        setMinimumSize(new java.awt.Dimension(460, 282));
        setResizable(false);
        setSize(new java.awt.Dimension(460, 282));

        JP1.setBackground(new java.awt.Color(255, 255, 255));
        JP1.setForeground(new java.awt.Color(255, 255, 255));
        JP1.setToolTipText("");
        JP1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        JP1.setMinimumSize(new java.awt.Dimension(460, 282));
        JP1.setPreferredSize(new java.awt.Dimension(460, 282));
        JP1.setLayout(null);

        JUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryManagementProgram/icon/Lock.jpg"))); // NOI18N
        JP1.add(JUserIcon);
        JUserIcon.setBounds(50, 250, 40, 40);

        JPassIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryManagementProgram/icon/key.jpg"))); // NOI18N
        JP1.add(JPassIcon);
        JPassIcon.setBounds(50, 320, 40, 40);

        JUserText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JUserText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JUserText.setToolTipText("");
        JUserText.setActionCommand("<Not Set>");
        JUserText.setBorder(null);
        JUserText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JUserText.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JUserText.setMinimumSize(new java.awt.Dimension(4, 26));
        JUserText.setPreferredSize(new java.awt.Dimension(206, 30));
        JUserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUserTextActionPerformed(evt);
            }
        });
        JP1.add(JUserText);
        JUserText.setBounds(118, 250, 300, 45);

        JPassTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JPassTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JPassTxt.setBorder(null);
        JPassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPassTxtActionPerformed(evt);
            }
        });
        JP1.add(JPassTxt);
        JPassTxt.setBounds(118, 318, 300, 46);

        JLoginB.setBackground(new java.awt.Color(51, 0, 204));
        JLoginB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JLoginB.setForeground(new java.awt.Color(255, 255, 255));
        JLoginB.setText("Login");
        JLoginB.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JLoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLoginBActionPerformed(evt);
            }
        });
        JP1.add(JLoginB);
        JLoginB.setBounds(120, 420, 220, 70);

        JLReLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JP1.add(JLReLogin);
        JLReLogin.setBounds(48, 370, 360, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryManagementProgram/icon/loginFRAME.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        JP1.add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPassTxtActionPerformed

    private void JUserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUserTextActionPerformed

    private void JLoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLoginBActionPerformed
        // TODO add your handling code here:
        if (JUserText.getText().equals("admin")&&JPassTxt.getText().equals("admin")) {
            setVisible(false);
            AdminFrame ob=new AdminFrame();
            ob.setVisible(true);
        }  else {
            
            JLReLogin.setForeground(new java.awt.Color( 255,0, 0));
            JLReLogin.setText("Incorrect password");
            String sql="select * from account where Username=? and Password=?";
                try {
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,JUserText.getText() );
                    pst.setString(2,JPassTxt.getText() );
                    rs=pst.executeQuery();
                    if (rs.next()) {
                        rs.close();
                        pst.close();
                        
                        setVisible(false);
                        LibraryFrame ob=new LibraryFrame();
                        ob.setVisible(true);
                    } else {
                        JLReLogin.setForeground(new java.awt.Color( 255,0, 0));
                        JLReLogin.setText("Incorrect password");
                    }
                    }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, "loi ko xac ding"); 
                }
    }//GEN-LAST:event_JLoginBActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLReLogin;
    private javax.swing.JButton JLoginB;
    private javax.swing.JPanel JP1;
    private javax.swing.JLabel JPassIcon;
    private javax.swing.JPasswordField JPassTxt;
    private javax.swing.JLabel JUserIcon;
    private javax.swing.JTextField JUserText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
