/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMP.View;
import java.sql.*;
import LMP.Control.ConnectData;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class SignupFrame extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form Signup
     */
    public SignupFrame() {
        super("Login");
        initComponents();
        conn=ConnectData.getConnection();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP = new javax.swing.JPanel();
        JUser = new javax.swing.JLabel();
        JUserNameTxt = new javax.swing.JTextField();
        JPass = new javax.swing.JLabel();
        PasswordText = new javax.swing.JTextField();
        JBCreate = new javax.swing.JButton();
        JBBack = new javax.swing.JButton();
        JBCheck = new javax.swing.JButton();
        JCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management Program");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(550, 195, 514, 314));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(514, 314));
        setResizable(false);

        JP.setBackground(new java.awt.Color(255, 255, 255));
        JP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3), "New Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 102, 255))); // NOI18N

        JUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JUser.setText("Username");

        JUserNameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JUserNameTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JUserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUserNameTxtActionPerformed(evt);
            }
        });

        JPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JPass.setText("Password");

        PasswordText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasswordText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PasswordText.setEnabled(false);

        JBCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBCreate.setText("Create");
        JBCreate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JBCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCreateActionPerformed(evt);
            }
        });

        JBBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBBack.setText("Back");
        JBBack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBackActionPerformed(evt);
            }
        });

        JBCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBCheck.setText("Check");
        JBCheck.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JBCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCheckActionPerformed(evt);
            }
        });

        JCheck.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCheck.setForeground(new java.awt.Color(255, 255, 255));
        JCheck.setEnabled(false);

        javax.swing.GroupLayout JPLayout = new javax.swing.GroupLayout(JP);
        JP.setLayout(JPLayout);
        JPLayout.setHorizontalGroup(
            JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(JBCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPLayout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(JCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPLayout.createSequentialGroup()
                        .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JUser)
                            .addComponent(JPass))
                        .addGap(73, 73, 73)
                        .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordText)
                            .addComponent(JUserNameTxt))))
                .addGap(18, 18, 18))
        );
        JPLayout.setVerticalGroup(
            JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(JCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JUserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUserNameTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JUserNameTxtActionPerformed

    private void JBCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCreateActionPerformed
        // TODO add your handling code here:
        try {
            String sql="Insert into account(Username,Password) values(?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,JUserNameTxt.getText());
            pst.setString(2,PasswordText.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "New Account Created ");
            if (JOptionPane.OK_OPTION==JOptionPane.OK_OPTION) {
                setVisible(false);
                AdminFrame ob=new AdminFrame();
                ob.setVisible(true);
            }
            rs.close();
            pst.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_JBCreateActionPerformed

    private void JBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdminFrame ob=new AdminFrame();
        ob.setVisible(true);
    }//GEN-LAST:event_JBBackActionPerformed

    private void JBCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCheckActionPerformed
        // TODO add your handling code here:
        if (JUserNameTxt.isEnabled()==false) {
            PasswordText.setEnabled(false);
            JCheck.setSelected(false);
            JCheck.setText("");
            JUserNameTxt.setEnabled(true);
            PasswordText.setText("");
            JBCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryManagementProgram/icon/check.jpg")));
            JBCheck.setText("Check");
            
        } else 
        {
           if(JUserNameTxt.getText().toLowerCase().equals("admin")||JUserNameTxt.getText().equals("")){
                JCheck.setForeground(new java.awt.Color( 255,0, 0));
                JCheck.setText("You cannot create using this Username");
                PasswordText.setEnabled(false);
                PasswordText.setText("");
                
            }else{
                /*JCheck.setForeground(new java.awt.Color(0, 255, 0));
                JCheck.setText("Username can use");
                JCheck.setSelected(true);
                PasswordText.setEnabled(true);
                JUserNameTxt.setEnabled(false);
                JBCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryManagementProgram/icon/change.png"))); // NOI18N
                JBCheck.setText("Change");*/
                String sql="select Username from account where Username=?";
                try {
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,JUserNameTxt.getText() );
                    rs=pst.executeQuery();
                if (rs.next()) {
                    JCheck.setForeground(new java.awt.Color( 255,0, 0));
                    JCheck.setText("Username was created");
                    PasswordText.setEnabled(false);
                    rs.close();
                }else {
                    JCheck.setForeground(new java.awt.Color(0, 255, 0));
                    JCheck.setText("Username can use");
                    JCheck.setSelected(true);
                    PasswordText.setEnabled(true);
                    JUserNameTxt.setEnabled(false); // NOI18N
                    JBCheck.setText("Change");
                    
               }
                }catch(Exception e)
                    {
                            JOptionPane.showMessageDialog(null, "loi ko xac ding"); ;
                    }
            } 
        }
        
    }//GEN-LAST:event_JBCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBack;
    private javax.swing.JButton JBCheck;
    private javax.swing.JButton JBCreate;
    private javax.swing.JCheckBox JCheck;
    private javax.swing.JPanel JP;
    private javax.swing.JLabel JPass;
    private javax.swing.JLabel JUser;
    private javax.swing.JTextField JUserNameTxt;
    private javax.swing.JTextField PasswordText;
    // End of variables declaration//GEN-END:variables
}
