package LMP.View;

//import LMP.BussinessObject.Item;
import LMP.Model.View;
import LMP.Control.ViewAccess;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;

import java.io.File;
import java.io.IOException;

import java.text.MessageFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

import javax.swing.table.DefaultTableModel;

public class ViewView extends javax.swing.JFrame {

    ViewAccess ViewDB = new ViewAccess();

    Vector<String> header = new Vector<>();
    Vector data = new Vector();
    public String pathImageReader = null;
    public String pathImageBook = null;

    public ViewView() {
        initComponents();
        //Columns Headers
        header.add("Reader ID");
        header.add("Book ID");
        header.add("Borrowed date");
        header.add("Return date");
        //header.add("Imagebook");
        //Show all of Reader (Table) 
        getView();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tablebox = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        jPanelEditBox = new javax.swing.JPanel();
        PanelImage = new javax.swing.JPanel();
        Imagebox = new javax.swing.JLabel();
        LabelImagebook = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelImage1 = new javax.swing.JPanel();
        Imagebox1 = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        PanelButton = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        PanelSearch = new javax.swing.JPanel();
        jLabelSearchBy = new javax.swing.JLabel();
        cbbSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View");
        setResizable(false);

        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        Tablebox.setViewportView(tblBook);

        jPanelEditBox.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        PanelImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Imagebox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMP/Image/NoImage/NoImage.png"))); // NOI18N
        Imagebox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LabelImagebook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelImagebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagebook.setText(" Reader");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ID Reader");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Name");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelImageLayout = new javax.swing.GroupLayout(PanelImage);
        PanelImage.setLayout(PanelImageLayout);
        PanelImageLayout.setHorizontalGroup(
            PanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagebox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelImagebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelImageLayout.setVerticalGroup(
            PanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImageLayout.createSequentialGroup()
                .addGroup(PanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelImageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelImagebook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelImageLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Imagebox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Borrowed date");

        PanelImage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Imagebox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMP/Image/NoImage/NoImage.png"))); // NOI18N
        Imagebox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Error1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Error1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Error1.setText("Book");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID Book");

        javax.swing.GroupLayout PanelImage1Layout = new javax.swing.GroupLayout(PanelImage1);
        PanelImage1.setLayout(PanelImage1Layout);
        PanelImage1Layout.setHorizontalGroup(
            PanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Error1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Imagebox1)
                .addContainerGap())
        );
        PanelImage1Layout.setVerticalGroup(
            PanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Error1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImage1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imagebox1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Return date");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanelEditBoxLayout = new javax.swing.GroupLayout(jPanelEditBox);
        jPanelEditBox.setLayout(jPanelEditBoxLayout);
        jPanelEditBoxLayout.setHorizontalGroup(
            jPanelEditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelEditBoxLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addComponent(PanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditBoxLayout.createSequentialGroup()
                        .addComponent(jTextField2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(PanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelEditBoxLayout.setVerticalGroup(
            jPanelEditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 42, Short.MAX_VALUE)
                .addGroup(jPanelEditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonLayout = new javax.swing.GroupLayout(PanelButton);
        PanelButton.setLayout(PanelButtonLayout);
        PanelButtonLayout.setHorizontalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnPrint)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap())
        );
        PanelButtonLayout.setVerticalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnExit)
                    .addComponent(btnPrint))
                .addContainerGap())
        );

        PanelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        PanelSearch.setPreferredSize(new java.awt.Dimension(883, 80));

        jLabelSearchBy.setText("Search by");

        cbbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BookID", "ReaderID", "Borrowed date", "Return date", "All" }));
        cbbSearch.setSelectedIndex(4);
        cbbSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSearchLayout = new javax.swing.GroupLayout(PanelSearch);
        PanelSearch.setLayout(PanelSearchLayout);
        PanelSearchLayout.setHorizontalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearchBy)
                .addGap(26, 26, 26)
                .addComponent(cbbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addGap(19, 19, 19))
        );
        PanelSearchLayout.setVerticalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(cbbSearch)
                    .addComponent(jLabelSearchBy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tablebox, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addComponent(jPanelEditBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tablebox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEditBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        setVisible(false);
        new LibraryFrame().setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    //Reader -> Table 
    private void getView() {
        //Get all of books 
        data = ViewDB.getAllView();
        //All of books -> Table
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tblBook.getModel();
        tblModel.setDataVector(data, header);
    }

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        String readerID = this.jTextField5.getText();
        String bookID = this.jTextField3.getText();
        String borr = this.jTextField1.getText();
        String Return = this.jTextField2.getText();
        //Check duplicate key
        View b = ViewDB.getView(readerID, bookID);
        if (b == null) {
            //Add book
            int n = ViewDB.addNewView(readerID, bookID, borr, Return);
            if (n == 1) {
                getView();
            } else {
                JOptionPane.showMessageDialog(this, "Add View failure!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Duplicate key!" + b);
        }

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            String readerID = this.jTextField5.getText();
            String bookID = this.jTextField3.getText();
            if (readerID == null && bookID == null) {
                JOptionPane.showMessageDialog(this, "Please chosse readerID and bookID to delete ");
                return;
            }
            int n = ViewDB.deleteView(readerID, bookID);
            if (n == 1) {
                getView();
            } else {
                JOptionPane.showMessageDialog(this, "Delete View failure!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (this.tblBook.getSelectedRow() == -1) {
            if (this.tblBook.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is empty!");
            } else {
                JOptionPane.showMessageDialog(this, "You must select a product");
            }
        } else {
            DefaultTableModel model = (DefaultTableModel) this.tblBook.getModel();
            String ReaderID = model.getValueAt(this.tblBook.getSelectedRow(), 0).toString();
            String BookID = model.getValueAt(this.tblBook.getSelectedRow(), 1).toString();
            String Borr = this.jTextField1.getText();
            String Return = this.jTextField2.getText();
            int n = ViewDB.updateView(ReaderID, BookID, Borr, Return);
            if (n == 1) {
                getView();
            } else {
                JOptionPane.showMessageDialog(this, "Update Reader failure!");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked
        int selectrow = tblBook.getSelectedRow();
        String tempImagePath;
        String tempImagePath1;
        if (selectrow >= 0) {
            if (tblBook.getValueAt(selectrow, 0) != null) {
                jTextField5.setText(tblBook.getValueAt(selectrow, 0).toString());
                tempImagePath = ViewDB.GetImageReader(jTextField5.getText());
                jTextField6.setText(ViewDB.GetNameReader(jTextField5.getText()));
            } else {
                jTextField5.setText("");
                jTextField6.setText("");
                tempImagePath = null;
            }
            if (tblBook.getValueAt(selectrow, 1) != null) {
                jTextField3.setText(tblBook.getValueAt(selectrow, 1).toString());
                tempImagePath1 = ViewDB.GetImageBook(jTextField3.getText());
                jTextField4.setText(ViewDB.GetTitleBook(jTextField3.getText()));
            } else {
                jTextField3.setText("");
                jTextField4.setText("");
                tempImagePath1 = null;
            }
            if (tblBook.getValueAt(selectrow, 2) != null) {
                jTextField1.setText(tblBook.getValueAt(selectrow, 2).toString());
            } else {
                jTextField1.setText("");
            }
            if (tblBook.getValueAt(selectrow, 3) != null) {
                jTextField2.setText(tblBook.getValueAt(selectrow, 3).toString());
            } else {
                jTextField2.setText("");
            }

            if (tempImagePath == null || "null".equals(tempImagePath)) {
                pathImageReader = null;
                Image bi;
                try {
                    bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                    Imagebox.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                    Imagebox.setIcon(new javax.swing.ImageIcon(ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " "))).getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                } catch (IOException ex) {

                }
            } else {
                pathImageReader = tempImagePath;
                try {
                    BufferedImage bi = ImageIO.read(new File(pathImageReader));
                    Imagebox.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));

                } catch (Exception e) {

                    pathImageReader = tempImagePath;
                    Image bi;
                    try {
                        bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                        Imagebox.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                    } catch (IOException ex) {
                    }
                }
            }
            if (tempImagePath1 == null || "null".equals(tempImagePath1)) {
                pathImageBook = null;
                Image bi;
                try {
                    bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                    Imagebox1.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                    Imagebox1.setIcon(new javax.swing.ImageIcon(ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " "))).getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                } catch (IOException ex) {

                }
            } else {
                pathImageBook = tempImagePath1;
                try {
                    BufferedImage bi = ImageIO.read(new File(pathImageBook));
                    Imagebox1.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));

                } catch (Exception e) {

                    pathImageBook = tempImagePath1;
                    Image bi;
                    try {
                        bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                        Imagebox1.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                    } catch (IOException ex) {
                    }
                }
            }
        }


    }//GEN-LAST:event_tblBookMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("Books");
        MessageFormat footer = new MessageFormat("");
        try {
            this.tblBook.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to print");
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        int pos = this.cbbSearch.getSelectedIndex();
        switch (pos) {
            case 0:
                data = ViewDB.searchByReaderID(this.txtSearch.getText());
                break;
            case 1:
                data = ViewDB.searchByBookID(this.txtSearch.getText());
                break;
            case 2:
                data = ViewDB.searchByBorr(this.txtSearch.getText());
                break;
            case 3:
                data = ViewDB.searchByReturn(this.txtSearch.toString());
                break;
            case 4:
                getView();
                break;
        }
        //Result -> Table
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tblBook.getModel();
        tblModel.setDataVector(data, header);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        getView();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cbbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbbSearchActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        if (jTextField3.getText() == null) {
            return;
        }
        pathImageBook = ViewDB.GetImageBook(jTextField3.getText());
        jTextField4.setText(ViewDB.GetTitleBook(jTextField3.getText()));
        if (pathImageBook == null || "null".equals(pathImageBook)) {
            Image bi;
            try {
                bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                Imagebox1.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                Imagebox1.setIcon(new javax.swing.ImageIcon(ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " "))).getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
            } catch (IOException ex) {

            }
        } else {
            try {
                BufferedImage bi = ImageIO.read(new File(pathImageBook));
                Imagebox1.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));

            } catch (Exception e) {
                Image bi;
                try {
                    bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                    Imagebox1.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                } catch (IOException ex) {
                }
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
        if (jTextField5.getText() == null) {

            return;
        }
        pathImageReader = ViewDB.GetImageReader(jTextField5.getText());
        jTextField6.setText(ViewDB.GetNameReader(jTextField5.getText()));
        if (pathImageReader == null || "null".equals(pathImageReader)) {
            Image bi;
            try {
                bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                Imagebox.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                Imagebox.setIcon(new javax.swing.ImageIcon(ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " "))).getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
            } catch (IOException ex) {

            }
        } else {
            try {
                BufferedImage bi = ImageIO.read(new File(pathImageReader));
                Imagebox.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));

            } catch (Exception e) {
                Image bi;
                try {
                    bi = ImageIO.read(new File(getClass().getResource("/LMP/Image/NoImage/NoImage.png").getPath().replace("%20", " ")));
                    Imagebox.setIcon(new javax.swing.ImageIcon(bi.getScaledInstance(140, 180, Image.SCALE_SMOOTH)));
                } catch (IOException ex) {
                }
            }
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Imagebox;
    private javax.swing.JLabel Imagebox1;
    private javax.swing.JLabel LabelImagebook;
    private javax.swing.JPanel PanelButton;
    private javax.swing.JPanel PanelImage;
    private javax.swing.JPanel PanelImage1;
    private javax.swing.JPanel PanelSearch;
    private javax.swing.JScrollPane Tablebox;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSearchBy;
    private javax.swing.JPanel jPanelEditBox;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
